### ISSUE TITLE
Preview plugin crashes

### ISSUE THREAD

**Issue by tonyshkurenko** [Kotlin/anko#111]
DSL Preview crashes in Android Studio. Re-installing didn't help.

Here is copied stacktrace:

```
org.jetbrains.kotlin.idea.internal.Location.getJetFile()Lorg/jetbrains/kotlin/psi/KtFile;
java.lang.NoSuchMethodError: org.jetbrains.kotlin.idea.internal.Location.getJetFile()Lorg/jetbrains/kotlin/psi/KtFile;
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager$UpdateActivityNameTask.prepareRequestInfo(DslPreviewToolWindowManager.kt:382)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager$UpdateActivityNameTask.prepareRequestInfo(DslPreviewToolWindowManager.kt:369)
	at org.jetbrains.kotlin.idea.util.LongRunningReadTask.init(LongRunningReadTask.java:136)
	at org.jetbrains.kotlin.idea.util.InfinitePeriodicalTask$1.run(InfinitePeriodicalTask.java:46)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



java.lang.NoSuchMethodError: org.jetbrains.kotlin.idea.internal.Location.getJetFile()Lorg/jetbrains/kotlin/psi/KtFile;
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager$UpdateActivityNameTask.prepareRequestInfo(DslPreviewToolWindowManager.kt:382)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager$UpdateActivityNameTask.prepareRequestInfo(DslPreviewToolWindowManager.kt:369)
	at org.jetbrains.kotlin.idea.util.LongRunningReadTask.init(LongRunningReadTask.java:136)
	at org.jetbrains.kotlin.idea.util.InfinitePeriodicalTask$1.run(InfinitePeriodicalTask.java:46)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



java.lang.NoSuchMethodError: org.jetbrains.kotlin.idea.internal.Location.getJetFile()Lorg/jetbrains/kotlin/psi/KtFile;
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager$UpdateActivityNameTask.prepareRequestInfo(DslPreviewToolWindowManager.kt:382)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager$UpdateActivityNameTask.prepareRequestInfo(DslPreviewToolWindowManager.kt:369)
	at org.jetbrains.kotlin.idea.util.LongRunningReadTask.init(LongRunningReadTask.java:136)
	at org.jetbrains.kotlin.idea.util.InfinitePeriodicalTask$1.run(InfinitePeriodicalTask.java:46)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)


```

**Comment by rondou** [comment]
me too

**Comment by gabriel-fallen** [comment]
Crashes with the same message (and couple similar messages) in IDEA Community 15.
Preview plugin version is 0.7.3a.

**Comment by yanex** [comment]
Anko 0.8 contains the new DSL Preview Plugin, so this issue is considered obsolete now.
Please create a new issue if the exception still remains in your case.
