### ISSUE TITLE
Anko DSL Preview plugin 0.8 crashes

### ISSUE THREAD

**Issue by gabriel-fallen** [Kotlin/anko#115]
With this error message:
NoSuchMethodError: kotlin.StringsKt.isNotBlank(Ljava/lang/CharSequence;)Z

Is it an issue with Kotlin version?
I use Kotlin 1.0.0-beta-2423 in the project (configured with Gradle) and a plugin with the same version.

**Comment by yanex** [comment]
What IDE to you use? AS/IDEA? Version?

**Comment by gabriel-fallen** [comment]
I'm using IDEA 15 community.

I'm sorry I couldn't provide full stacktrace and version of IDE. Plugin crash disturbed work of IDEA so I couldn't copy-paste text and had to disable plugin and restart.

**Comment by gabriel-fallen** [comment]
As far as I understood from the stackrace the exception is caused by some combobox on the plugin panel. I guess it's the combobox for AnkoComponent class selection for preview.

At the moment I don't have access to that working environment. I'll be able to provide additional details this evening (Moscow time).

Thanks!

**Comment by autrilla** [comment]
I have the same issue too. I'm using IntelliJ IDEA 15, and here's the stacktrace:

```
kotlin.StringsKt.isNotBlank(Ljava/lang/CharSequence;)Z
	java.lang.NoSuchMethodError: kotlin.StringsKt.isNotBlank(Ljava/lang/CharSequence;)Z
		at org.jetbrains.kotlin.android.dslpreview.PreviewClassDescription.toString(PreviewClassDescription.kt:26)
		at javax.swing.plaf.basic.BasicComboBoxRenderer.getListCellRendererComponent(BasicComboBoxRenderer.java:121)
		at com.intellij.openapi.ui.ComboBoxWithWidePopup$AdjustingListCellRenderer.getListCellRendererComponent(ComboBoxWithWidePopup.java:120)
		at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1361)
		at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1311)
		at javax.swing.plaf.basic.BasicListUI$Handler.valueChanged(BasicListUI.java:2623)
		at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
		at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
		at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
		at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
		at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
		at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
		at javax.swing.JList.setSelectedIndex(JList.java:2210)
		at javax.swing.plaf.basic.BasicComboPopup.setListSelection(BasicComboPopup.java:1168)
		at javax.swing.plaf.basic.BasicComboPopup.access$300(BasicComboPopup.java:63)
		at javax.swing.plaf.basic.BasicComboPopup$Handler.itemStateChanged(BasicComboPopup.java:999)
		at javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1223)
		at javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1280)
		at javax.swing.JComboBox.contentsChanged(JComboBox.java:1330)
		at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
		at javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:93)
		at javax.swing.DefaultComboBoxModel.addElement(DefaultComboBoxModel.java:131)
		at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager.resolveAvailableClasses(DslPreviewToolWindowManager.kt:266)
		at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager.initToolWindow(DslPreviewToolWindowManager.kt:148)
		at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$5.run(AndroidLayoutPreviewToolWindowManager.java:480)
		at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
		at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
		at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
		at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2321)
		at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:283)
		at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
		at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
		at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
		at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
		at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
		at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
		at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
		at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)



	java.lang.NoSuchMethodError: kotlin.StringsKt.isNotBlank(Ljava/lang/CharSequence;)Z
		at org.jetbrains.kotlin.android.dslpreview.PreviewClassDescription.toString(PreviewClassDescription.kt:26)
		at javax.swing.plaf.basic.BasicComboBoxRenderer.getListCellRendererComponent(BasicComboBoxRenderer.java:121)
		at com.intellij.openapi.ui.ComboBoxWithWidePopup$AdjustingListCellRenderer.getListCellRendererComponent(ComboBoxWithWidePopup.java:120)
		at com.intellij.ide.ui.laf.darcula.ui.DarculaComboBoxUI.getDisplaySize(DarculaComboBoxUI.java:159)
		at javax.swing.plaf.basic.BasicComboBoxUI.getMinimumSize(BasicComboBoxUI.java:934)
		at javax.swing.plaf.basic.BasicComboBoxUI.getPreferredSize(BasicComboBoxUI.java:923)
		at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
		at com.intellij.openapi.ui.ComboBox.getPreferredSize(ComboBox.java:268)
		at com.intellij.openapi.ui.ComboBox.getMinimumSize(ComboBox.java:263)
		at com.intellij.uiDesigner.core.Util.getMinimumSize(Util.java:27)
		at com.intellij.uiDesigner.core.DimensionInfo.getMinimumSize(DimensionInfo.java:239)
		at com.intellij.uiDesigner.core.HorizontalInfo.getMinimumWidth(HorizontalInfo.java:40)
		at com.intellij.uiDesigner.core.GridLayoutManager.getMin2(GridLayoutManager.java:734)
		at com.intellij.uiDesigner.core.GridLayoutManager.getMinOrPrefSizes(GridLayoutManager.java:645)
		at com.intellij.uiDesigner.core.GridLayoutManager.getMinSizes(GridLayoutManager.java:626)
		at com.intellij.uiDesigner.core.GridLayoutManager.minimumLayoutSize(GridLayoutManager.java:221)
		at java.awt.Container.minimumSize(Container.java:1848)
		at java.awt.Container.getMinimumSize(Container.java:1832)
		at javax.swing.JComponent.getMinimumSize(JComponent.java:1746)
		at com.intellij.uiDesigner.core.Util.getMinimumSize(Util.java:27)
		at com.intellij.uiDesigner.core.DimensionInfo.getMinimumSize(DimensionInfo.java:239)
		at com.intellij.uiDesigner.core.HorizontalInfo.getMinimumWidth(HorizontalInfo.java:40)
		at com.intellij.uiDesigner.core.GridLayoutManager.getMinOrPrefSizes(GridLayoutManager.java:645)
		at com.intellij.uiDesigner.core.GridLayoutManager.getPrefSizes(GridLayoutManager.java:630)
		at com.intellij.uiDesigner.core.GridLayoutManager.preferredLayoutSize(GridLayoutManager.java:274)
		at com.intellij.uiDesigner.core.GridLayoutManager.layoutContainer(GridLayoutManager.java:409)
		at java.awt.Container.layout(Container.java:1510)
		at java.awt.Container.doLayout(Container.java:1499)
		at java.awt.Container.validateTree(Container.java:1695)
		at java.awt.Container.validateTree(Container.java:1704)
		at java.awt.Container.validateTree(Container.java:1704)
		at java.awt.Container.validateTree(Container.java:1704)
		at java.awt.Container.validateTree(Container.java:1704)
		at java.awt.Container.validateTree(Container.java:1704)
		at java.awt.Container.validateTree(Container.java:1704)
		at java.awt.Container.validateTree(Container.java:1704)
		at java.awt.Container.validateTree(Container.java:1704)
		at java.awt.Container.validateTree(Container.java:1704)
		at java.awt.Container.validateTree(Container.java:1704)
		at java.awt.Container.validate(Container.java:1630)
		at com.intellij.openapi.wm.impl.ToolWindowsPane$AddDockedComponentCmd.run(ToolWindowsPane.java:754)
		at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
		at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
		at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
		at java.awt.EventQueue.access$500(EventQueue.java:97)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.awt.EventQueue$3.run(EventQueue.java:703)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
		at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by DmitriyZaitsev** [comment]
+1
Android Studio 2.0 Preview 2
