### ISSUE TITLE
XML -> DSL converter crash (v0.8.1)

### ISSUE THREAD

**Issue by DmitriyZaitsev** [Kotlin/anko#121]
Repro steps:
1. Open any xml layout
2. Code -> Convert to Koan DSL
...
4. Anko DSL Preview threw an uncaught NoClassDefFoundError.

**IDE**: *Android Studio 2.0 Preview 2*
**Kotlin**: *v1.0 Beta 3*
>
kotlinx/dom/DomKt
java.lang.NoClassDefFoundError: kotlinx/dom/DomKt
	at org.jetbrains.kotlin.android.xmlconverter.XmlConverter.parseView(XmlConverter.kt:85)
	at org.jetbrains.kotlin.android.xmlconverter.XmlConverter.convert(XmlConverter.kt:51)
	at org.jetbrains.kotlin.android.xmlconverter.XmlConverter.convert$default(XmlConverter.kt:47)
	at org.jetbrains.kotlin.android.xmlconverter.ConvertAction.convert(ConvertAction.kt:147)
	at org.jetbrains.kotlin.android.xmlconverter.ConvertAction.access$convert(ConvertAction.kt:40)
	at org.jetbrains.kotlin.android.xmlconverter.ConvertAction$actionPerformed$1.run(ConvertAction.kt:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1002)
	at org.jetbrains.kotlin.android.xmlconverter.ConvertAction.actionPerformed(ConvertAction.kt:51)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:311)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:281)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2028)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2351)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:387)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:291)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:389)
	at com.apple.laf.ScreenMenuItemCheckbox.itemStateChanged(ScreenMenuItemCheckbox.java:178)
	at java.awt.CheckboxMenuItem.processItemEvent(CheckboxMenuItem.java:372)
	at java.awt.CheckboxMenuItem.processEvent(CheckboxMenuItem.java:340)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:343)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:331)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:720)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by yanex** [comment]
Fixed in Anko DSL Preview IDEA Plugin 0.8.1a.

**Comment by hasanOryx** [comment]
I've the same issue with plugin 0.10.2
