### ISSUE TITLE
Kotlin threw an uncaught AbstractMethodError

### ISSUE THREAD

**Issue by GeorgeskyyyZD** [Kotlin/anko#229]
Hi all
My IDE is Android Studio 2.1.2 with the Kotlin plugin 
this error display Every seconds!
Is that my IDE  fault? or something haven't set corrected?

here is my build.gradle setting

`      
        apply plugin: 'com.android.application'
        apply plugin: 'kotlin-android'
        apply plugin: 'android-apt'
    
        android {
            compileSdkVersion 24
            buildToolsVersion "24.0.0"

            defaultConfig {
                applicationId "com.demonknoxkyo.consolidateknowledgeprogram"
                minSdkVersion 19
                targetSdkVersion 24
                versionCode 1
                versionName "1.0"
            }

            sourceSets {
                main {
                    manifest.srcFile 'src/main/AndroidManifest.xml'
                    java.srcDirs = ['src/main/java', '.apt_generated']
                    aidl.srcDirs = ['src/main/aidl', '.apt_generated']
                    jniLibs.srcDirs = ['src/main/jniLibs']
                    assets.srcDirs = ['assets']
                    res.srcDirs = [
                            'src/main/res/',
                            'src/main/res/anim',
                            'src/main/res/home'
                    ]
                }
                main.java.srcDirs += 'src/main/kotlin'
            }

            buildTypes {
                release {
                    minifyEnabled false
                    proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
                }
            }
        }

        buildscript {
            repositories {
                mavenCentral()
            }
            dependencies {
                classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
            }
        }

        dependencies {
            compile fileTree(include: ['*.jar'], dir: 'libs')
            compile 'com.android.support:appcompat-v7:24.0.0'
            compile 'com.android.support:support-v13:24.0.0'
            compile 'com.android.support:recyclerview-v7:24.0.0'

            compile 'com.jakewharton:butterknife:8.2.1'
            apt 'com.jakewharton:butterknife-compiler:8.2.1'
            compile 'com.github.bumptech.glide:glide:3.7.0'
            compile 'jp.wasabeef:glide-transformations:1.0.6'

            //kotlin and anko
            compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
            compile "org.jetbrains.anko:anko-sdk19:$anko_version" // sdk19, sdk21, sdk23 are also available
            compile "org.jetbrains.anko:anko-support-v4:$anko_version" // In case you need support-v4 bindings
            compile "org.jetbrains.anko:anko-appcompat-v7:$anko_version" // For appcompat-v7 bindings
            compile "org.jetbrains.anko:anko-cardview-v7:$anko_version"
            compile "org.jetbrains.anko:anko-gridlayout-v7:$anko_version"
            compile "org.jetbrains.anko:anko-recyclerview-v7:$anko_version"
            compile "org.jetbrains.anko:anko-design:$anko_version"
            compile "org.jetbrains.anko:anko-percent:$anko_version"
        }
        repositories {
            mavenCentral()
        }
`

here is my error
`null
java.lang.AbstractMethodError
	at org.jetbrains.kotlin.idea.intentions.SelfTargetingIntention.getTarget(SelfTargetingIntention.kt:75)
	at org.jetbrains.kotlin.idea.intentions.SelfTargetingIntention.isAvailable(SelfTargetingIntention.kt:86)
	at com.intellij.codeInsight.intention.impl.config.IntentionActionWrapper.isAvailable(IntentionActionWrapper.java:56)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.isAvailableHere(ShowIntentionActionsHandler.java:132)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.availableFor(ShowIntentionActionsHandler.java:113)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:304)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass$3.process(ShowIntentionsPass.java:301)
	at com.intellij.codeInsight.intention.impl.ShowIntentionActionsHandler.chooseBetweenHostAndInjected(ShowIntentionActionsHandler.java:157)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getActionsToShow(ShowIntentionsPass.java:301)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.getIntentionActionsToShow(ShowIntentionsPass.java:222)
	at com.intellij.codeInsight.daemon.impl.ShowIntentionsPass.doCollectInformation(ShowIntentionsPass.java:198)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1180)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)`

**Comment by cryser29** [comment]
I'm getting the same error +1

**Comment by yole** [comment]
The error is caused by an incompatibility between the Anko DSL preview plugin and Kotlin 1.0.3. You can disable it until a compatible update is released.

**Comment by cryser29** [comment]
@yole Thanks! I works for me
