### ISSUE TITLE
java.lang.NoSuchMethodError: android.view.ContextThemeWrapper.getThemeResId

### ISSUE THREAD

**Issue by mvysny** [Kotlin/anko#236]
On the SDK 10 Emulator I'm getting the following stack trace:

```
08-23 22:58:15.210 1181-1181/sk.baka.aedict3 E/AndroidRuntime: FATAL EXCEPTION: main
                                                               java.lang.NoSuchMethodError: android.view.ContextThemeWrapper.getThemeResId
                                                                   at org.jetbrains.anko.internals.AnkoInternals.wrapContextIfNeeded(Internals.kt:58)
                                                                   at sk.baka.aedict3.unitedkanjisearch.KanjiDrawFragment.onCreateView(KanjiDrawFragment.kt:190)
                                                                   at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                   at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                   at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                   at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
                                                                   at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:452)
                                                                   at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:141)
                                                                   at android.app.Activity.performResume(Activity.java:3841)
                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2110)
                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2135)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1668)
                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:117)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                   at android.os.Looper.loop(Looper.java:130)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:3683)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:507)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
                                                                   at dalvik.system.NativeStart.main(Native Method)
```

The problem is that pesky `getThemeResId()` function, which is undocumented (It is marked as /*\* @hide */ in the ContextThemeWrapper source code; it is also not present in the Android javadoc at https://developer.android.com/reference/android/view/ContextThemeWrapper.html

Apparently, on the Emulator the function is unimplemented, yet apparently on the real devices the function works correctly, otherwise I would be getting tons of crash reports.

**Comment by fboldog** [comment]
related #206

**Comment by yanex** [comment]
Anko officially supports Android SDK starting from the version 15.

**Comment by mvysny** [comment]
I don't understand: the `getThemeResId()` function is not part of Android API, regardless of the SDK API version. Yet, ContextThemeWrapper in support library is also marked as "@hide", so I guess there is no way to detect the current Theme. Android is really not that open as I thought before.
