### ISSUE TITLE
preview plug not support for kotlin-1.0.4-release

### ISSUE THREAD

**Issue by AndwareSsj** [Kotlin/anko#252]
```
Plugin Error: Anko DSL Preview threw an uncaught NoClassDefFoundError. Disable Plugin
NoClassDefFoundError: org/jetbrains/kotlin/asJava/KtLightElement 
```

**Comment by hoha** [comment]
This is a report I've got from IntelliJ exception analyzer (Android Studio build 143.1821):

```
org/jetbrains/kotlin/asJava/KtLightElement

java.lang.NoClassDefFoundError: org/jetbrains/kotlin/asJava/KtLightElement
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager.getKtClass(DslPreviewToolWindowManager.kt:332)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager.resolveClassDescription(DslPreviewToolWindowManager.kt:366)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager.getAncestors(DslPreviewToolWindowManager.kt:354)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager.resolveAvailableClasses(DslPreviewToolWindowManager.kt:319)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager.initToolWindow(DslPreviewToolWindowManager.kt:162)
	at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$5.run(AndroidLayoutPreviewToolWindowManager.java:491)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2361)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:283)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: org.jetbrains.kotlin.asJava.KtLightElement PluginClassLoader[org.jetbrains.kotlin.android.dsl, 0.9b]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more
```

**Comment by leandroBorgesFerreira** [comment]
same here

**Comment by audax** [comment]
Will there be a fix for that or is the preview plugin deprecated/unmaintained?

**Comment by yanex** [comment]
See also #314.
