### ISSUE TITLE
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo

### ISSUE THREAD

**Issue by houskii** [Kotlin/anko#312]
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{***Activity}: java.lang.ClassNotFoundException: Didn't find class "***Activity" on path: DexPathList[[zip file "/data/app/***-1/base.apk"],nativeLibraryDirectories=[/data/app/***-1/lib/arm, /vendor/lib, /system/lib]]
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2290)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2442)
                                                               at android.app.ActivityThread.access$800(ActivityThread.java:156)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1351)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:211)
                                                               at android.app.ActivityThread.main(ActivityThread.java:5389)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
                                                               at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:115)

**Comment by yanex** [comment]
Does it have something to do with Anko?

**Comment by robinkanters** [comment]
@yanex getting this same issue with a clean project, only Anko installed, so it would seem so

**Comment by yanex** [comment]
Can you share the sample project then?

**Comment by yanex** [comment]
The issue is closed because of no response. Please file the new issue if the problem still exists.
