### ISSUE TITLE
NoSuchElementException when attempting to iterate over views

### ISSUE THREAD

**Issue by mvysny** [Kotlin/anko#335]
A very simple for loop (currently in Java, not yet converted to Kotlin, I apologize :-) ):

```java
for (Iterator<View> i = ViewChildrenSequencesKt.childrenRecursiveSequence(KViewsKt.getRoot(fm)).iterator(); i.hasNext(); ) {
            final View view = i.next();
```

(the `getRoot()` looks like this:
```
val Activity.root: View get() = findViewById(android.R.id.content)!!
```

fails with

```
java.util.NoSuchElementException
at org.jetbrains.anko.ViewChildrenRecursiveSequence$RecursiveViewIterator.next(viewChildrenSequences.kt:128)
at org.jetbrains.anko.ViewChildrenRecursiveSequence$RecursiveViewIterator.next(viewChildrenSequences.kt:122)
```
This is for Anko 0.9

**Comment by mvysny** [comment]
Also reproducible with Anko 0.9.1a:

```
java.util.NoSuchElementException
at org.jetbrains.anko.ViewChildrenRecursiveSequence$RecursiveViewIterator.next(viewChildrenSequences.kt:129)
at org.jetbrains.anko.ViewChildrenRecursiveSequence$RecursiveViewIterator.next(viewChildrenSequences.kt:123)
```

**Comment by semenoh** [comment]
same issue
