### ISSUE TITLE
java.util.regex.PatternSyntaxException: Syntax error in regexp pattern

### ISSUE THREAD

**Issue by poovarasanvasudevan** [Kotlin/anko#345]
I using anko 0.10.0-beta-1( compile 'org.jetbrains.anko:anko-sqlite:0.10.0-beta-1'), Using sqlite Iam causing this Exception 

`Caused by: java.lang.ExceptionInInitializerError
                                                              at com.shpt.core.db.DatabaseOpenHelper.onCreate(DatabaseOpenHelper.kt:33)
                                                              at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
                                                              at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                              at org.jetbrains.anko.db.ManagedSQLiteOpenHelper.openDatabase(Database.kt:166)
                                                              at org.jetbrains.anko.db.ManagedSQLiteOpenHelper.use(Database.kt:157)
                                                              at com.shpt.MainActivity$DownloadKernel.doInBackground(MainActivity.kt:76)
                                                              at com.shpt.MainActivity$DownloadKernel.doInBackground(MainActivity.kt:72)
                                                              at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                              at java.lang.Thread.run(Thread.java:818) 
                                                           Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 18:
                                                          ([^\\])\{([^{}]+)}
                                                                            ^
                                                              at java.util.regex.Pattern.compileImpl(Native Method)
                                                              at java.util.regex.Pattern.compile(Pattern.java:411)
                                                              at java.util.regex.Pattern.<init>(Pattern.java:394)
                                                              at java.util.regex.Pattern.compile(Pattern.java:381)
                                                              at org.jetbrains.anko.db.DatabaseKt.<clinit>(Database.kt:93)`

**Comment by LouisCAD** [comment]
Had the same issue. I commented the breaking change in the commit here: https://github.com/Kotlin/anko/commit/d57195f3461d666a7ccd5929c81579efe6708534#commitcomment-21486936

**Comment by LouisCAD** [comment]
The workaround is to use version `0.9.1` for the anko sqlite dependency. This doesn't appear to bring any conflict even if you use other anko libraries with version `0.10.0-beta-2`
