### ISSUE TITLE
Plugin Error: Anko Support threw an uncaught. Anko 0.10.0 and AS 3.0 C1 

### ISSUE THREAD

**Issue by antoniovj1** [Kotlin/anko#387]
![image](https://cloud.githubusercontent.com/assets/7096481/26308908/69796d1e-3efb-11e7-95cf-51d9056cd5f0.png)

![image](https://cloud.githubusercontent.com/assets/7096481/26308951/97d47e9c-3efb-11e7-99ec-956c9370f4fa.png)

**Comment by yanex** [comment]
Can you please share the exception stacktrace?

**Comment by antoniovj1** [comment]
This is the IDE Fatal Error details :
```
Access is allowed from event dispatch thread only.
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@194cf2af Current thread: Thread[ApplicationImpl pooled thread 11,4,main] 1960035280 SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 721795586

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:493)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:32)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1112)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1101)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.assertDispatchThread(FileEditorManagerImpl.java:1513)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getSelectedTextEditor(FileEditorManagerImpl.java:1196)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getSelectedTextEditor(FileEditorManagerImpl.java:1191)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewClassResolver.getOnCursorPreviewClassDescription(DslPreviewClassResolver.kt:47)
	at org.jetbrains.kotlin.android.dslpreview.AnkoNlPreviewManager.refresh(AnkoNlPreviewManager.kt:127)
	at org.jetbrains.kotlin.android.dslpreview.AnkoNlPreviewManager.access$refresh(AnkoNlPreviewManager.kt:38)
	at org.jetbrains.kotlin.android.dslpreview.AnkoNlPreviewManager$2.execute(AnkoNlPreviewManager.kt:71)
	at com.android.tools.idea.gradle.project.build.invoker.GradleTasksExecutor$GradleTasksExecutorImpl.lambda$showGradleOutput$4(GradleTasksExecutor.java:552)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
	at com.android.tools.idea.gradle.project.build.invoker.GradleTasksExecutor$GradleTasksExecutorImpl.lambda$collectMessages$5(GradleTasksExecutor.java:569)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```


And here all de infromation in threadDump.txt :100: : 

[threadDump.txt](https://github.com/Kotlin/anko/files/1019035/threadDump.txt)

**Comment by mengming** [comment]
I have the same problem. Any solution?

**Comment by strahe** [comment]
fixed?

**Comment by yizhongliu** [comment]
I have the same problem.  What is the solution

**Comment by ParkerK** [comment]
@yanex - The 10.0.1 plugin https://github.com/Kotlin/anko/releases/tag/v0.10.1 is not compatable with Android Studio 23, just an FYI

**Comment by dashracer** [comment]
I have the same problem. What is the solution.

**Comment by sinadarvi** [comment]
i still have this problem, what is the solution ?

**Comment by iam1492** [comment]
+1

**Comment by sw-alex-1** [comment]
I have same problem with plugin version 0.10.3, 
Android Studio 3.0.1 Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3

Access is allowed from event dispatch thread only.
 EventQueue.isDispatchThread()=false isDispatchThread()=false Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@3c6d078c Current thread: Thread[ApplicationImpl pooled thread 8,4,main] 969683659 SystemEventQueueThread: Thread[AWT-EventQueue-0 3.0#AI-171.4443003 Studio, eap:false, os:Windows 8.1 6.3, java-version:JetBrains s.r.o 1.8.0_152-release-915-b01,6,main] 1566906155

java.lang.Throwable
	at com.intellij.util.ExceptionUtil.currentStackTrace(ExceptionUtil.java:65)
	at com.intellij.psi.impl.DebugUtil.currentStackTrace(DebugUtil.java:493)
	at com.intellij.diagnostic.LogEventException.<init>(LogEventException.java:32)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1112)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1101)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.assertDispatchThread(FileEditorManagerImpl.java:1513)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getSelectedTextEditor(FileEditorManagerImpl.java:1196)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getSelectedTextEditor(FileEditorManagerImpl.java:1191)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewClassResolver$getOnCursorPreviewClassDescription$editor$1.compute(DslPreviewClassResolver.kt:49)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewClassResolver$getOnCursorPreviewClassDescription$editor$1.compute(DslPreviewClassResolver.kt:33)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:946)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewClassResolver.getOnCursorPreviewClassDescription(DslPreviewClassResolver.kt:48)
	at org.jetbrains.kotlin.android.dslpreview.AnkoNlPreviewManager.refresh(AnkoNlPreviewManager.kt:129)
	at org.jetbrains.kotlin.android.dslpreview.AnkoNlPreviewManager.access$refresh(AnkoNlPreviewManager.kt:40)
	at org.jetbrains.kotlin.android.dslpreview.AnkoNlPreviewManager$2.execute(AnkoNlPreviewManager.kt:73)
	at com.android.tools.idea.gradle.project.build.invoker.GradleTasksExecutorImpl.lambda$showGradleOutput$4(GradleTasksExecutorImpl.java:472)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
	at com.android.tools.idea.gradle.project.build.invoker.GradleTasksExecutorImpl.lambda$collectMessages$5(GradleTasksExecutorImpl.java:489)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
