### ISSUE TITLE
Anko Support Error

### ISSUE THREAD

**Issue by ywxt** [Kotlin/anko#394]
I can't preview a DSL layout.
```
com.android.tools.idea.uibuilder.editor.NlPreviewManager.getToolWindow()Lcom/intellij/openapi/wm/ToolWindow;
java.lang.NoSuchMethodError: com.android.tools.idea.uibuilder.editor.NlPreviewManager.getToolWindow()Lcom/intellij/openapi/wm/ToolWindow;
	at org.jetbrains.kotlin.android.dslpreview.AnkoNlPreviewManager.getToolWindow(AnkoNlPreviewManager.kt:77)
	at org.jetbrains.kotlin.android.dslpreview.UpdateActivityNameTask.prepareRequestInfo(UpdateActivityNameTask.kt:16)
	at org.jetbrains.kotlin.android.dslpreview.UpdateActivityNameTask.prepareRequestInfo(UpdateActivityNameTask.kt:12)
	at org.jetbrains.kotlin.idea.util.LongRunningReadTask.init(LongRunningReadTask.java:136)
	at org.jetbrains.kotlin.idea.util.InfinitePeriodicalTask$1.run(InfinitePeriodicalTask.java:46)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:224)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:314)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by yanex** [comment]
What Android Studio version do you use?

**Comment by jlandrum** [comment]
From what I understand, currently, the plugin depends on a few Android Studio release-specific objects. IntelliJ Ultimate EAP and the Android Studio preview builds have a new-ish layout editor which seems to interfere with the preview plugin working.
