### ISSUE TITLE
Crash when creating database with Anko

### ISSUE THREAD

**Issue by TanNTAPlus** [Kotlin/anko#408]
I use Anko for SQLite android with version in Gradle <anko_version = '0.10.0-beta-2'>
And this is class MySQLHelper
`class MySqlHelper(ctx: Context) : ManagedSQLiteOpenHelper(ctx, "mydb") {

    companion object {
        var tableName: String = "User"
        private var instance: MySqlHelper? = null
        @Synchronized
        fun getInstance(ctx: Context): MySqlHelper {
            if (instance == null) {
                instance = MySqlHelper(ctx.applicationContext)
            }
            return instance!!
        }
    }

    override fun onCreate(db: SQLiteDatabase) {
        val alst = Pair("id", INTEGER + UNIQUE + PRIMARY_KEY)
        val als2 = Pair("name", TEXT)
        val als3 = Pair("address", TEXT)
        val args: Array<Pair<String, SqlType>> = arrayOf(alst, als2, als3)
        db.createTable(tableName, ifNotExists = true, columns = *args)
    }

    override fun onUpgrade(db: SQLiteDatabase, oldVersion: Int, newVersion: Int) {
        db.dropTable("User", true)
    }
}
val Context.database: MySqlHelper
    get() = MySqlHelper.getInstance(applicationContext)
`

This is below i use for create (action click to Button)
`
val alst = Pair("id", INTEGER + UNIQUE + PRIMARY_KEY)
        val als2 = Pair("name", TEXT)
        val als3 = Pair("phone", TEXT)
        val args: Array<Pair<String, SqlType>> = arrayOf(alst, als2, als3)
        database.use {
            createTable("User", ifNotExists = true, columns = *args)
        }
`
I get Error (see Logcast)

> java.lang.ExceptionInInitializerError
                                                                        at org.jetbrains.anko.db.DatabaseKt.createTable(Database.kt)
                                                                        at xxx.application.database.MySqlHelper.onCreate(MySqlHelper.kt:29)
                                                                        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
                                                                        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                                        at org.jetbrains.anko.db.ManagedSQLiteOpenHelper.openDatabase(Database.kt:166)
                                                                        at org.jetbrains.anko.db.ManagedSQLiteOpenHelper.use(Database.kt:157)

I don't know why? Please help me

**Comment by 4u7** [comment]
Try Anko 0.10.2, fixed with a9fb477
