### ISSUE TITLE
View is already set Bug

### ISSUE THREAD

**Issue by MinkiPan** [Kotlin/anko#478]
>java.lang.IllegalStateException: View is already set: org.jetbrains.anko._LinearLayout{550317 V.E...... ......I. 0,0-0,0}
                                                                      at org.jetbrains.anko.AnkoContextImpl.alreadyHasView(AnkoContext.kt:114)
                                                                      at org.jetbrains.anko.AnkoContextImpl.addView(AnkoContext.kt:96)
                                                                      at org.jetbrains.anko.internals.AnkoInternals.addView(Internals.kt:45)
...

I don't know why it exactly crashes but see the following code:

```
 container.rebuildCrash {
            verticalLayout { 
                textView { //this doesn't crash 

                }
            }

            (1..10).forEach {
                verticalLayout {

                    textView { //this crashes why?
                    }
                }
            }
        }
```

```
    inline fun ViewGroup.rebuildCrash(init: AnkoContext<ViewGroup>.() -> Unit) {
        removeAllViews()
        addView(createAnkoContext(context, init).view)
    }
```

is this a bug actually or did I something wrong? why does it crash only in the loop?

**Comment by Aetherna** [comment]
Are u addding LinearLayout in loop on purpose or want to add TextViews to one LinearLayout?

**Comment by MinkiPan** [comment]
on purpose, I want 10 textviews in my linrarlayout

**Comment by JSila** [comment]
Have you solved the issue? I faced similar error and solved it by wrapping my layout definition with another linearLayout. IMO this error has to do with the fact there are more than one view at root level.

**Comment by at-vinhhuynh** [comment]
@MinkiPan 
try
```
...
(1..10).forEach {
                verticalLayout {
                    textView {
                         id = it
                    }
                }
            }
...
```
