### ISSUE TITLE
Android Studio 3.0 Anko Support Plugin Error

### ISSUE THREAD

**Issue by yaosongqwe** [Kotlin/anko#503]
Plugin Error: Anko Support threw an uncaught NoClassDefFoundError. Disable Plugin

**Comment by yaosongqwe** [comment]
anko_version = '0.10.2'
kotlin_version = '1.1.51'

**Comment by yaosongqwe** [comment]
Plugin version is also 0.10.2

**Comment by yaosongqwe** [comment]
when preview activity's UI：
The following classes could not be found:
- __anko.preview.View (Change to android.media.tv.TvView, Fix Build Path, Edit XML, Create Class)

**Comment by 4u7** [comment]
@yaosongqwe Could you post stacktrace of the exception?

**Comment by yaosongqwe** [comment]
sorry，the error just said so,
when I try to use Anko Layout preview.

**Comment by ivankolev** [comment]
Can confirm, the same happens to me. Here's the stack trace:
`2017-11-13 15:34:04,797 [ thread 72]  ERROR - plication.impl.ApplicationImpl - Access is allowed from event dispatch thread only. 
com.intellij.diagnostic.LogEventException: Access is allowed from event dispatch thread only.
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1112)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertIsDispatchThread(ApplicationImpl.java:1101)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.assertDispatchThread(FileEditorManagerImpl.java:1513)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getSelectedTextEditor(FileEditorManagerImpl.java:1196)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getSelectedTextEditor(FileEditorManagerImpl.java:1191)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewClassResolver.getOnCursorPreviewClassDescription(DslPreviewClassResolver.kt:47)
	at org.jetbrains.kotlin.android.dslpreview.AnkoNlPreviewManager.refresh(AnkoNlPreviewManager.kt:129)
	at org.jetbrains.kotlin.android.dslpreview.AnkoNlPreviewManager.access$refresh(AnkoNlPreviewManager.kt:40)
	at org.jetbrains.kotlin.android.dslpreview.AnkoNlPreviewManager$2.execute(AnkoNlPreviewManager.kt:73)
	at com.android.tools.idea.gradle.project.build.invoker.GradleTasksExecutorImpl.lambda$showGradleOutput$4(GradleTasksExecutorImpl.java:472)
	at com.intellij.openapi.util.ExecutionCallback.setExecuted(ExecutionCallback.java:58)
	at com.intellij.openapi.util.ActionCallback.setDone(ActionCallback.java:72)
	at com.android.tools.idea.gradle.project.build.invoker.GradleTasksExecutorImpl.lambda$collectMessages$5(GradleTasksExecutorImpl.java:489)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-11-13 15:34:04,799 [ thread 72]  ERROR - plication.impl.ApplicationImpl - Android Studio 3.0  Build #AI-171.4408382 
2017-11-13 15:34:04,799 [ thread 72]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_152-release 
2017-11-13 15:34:04,799 [ thread 72]  ERROR - plication.impl.ApplicationImpl - VM: OpenJDK 64-Bit Server VM 
2017-11-13 15:34:04,799 [ thread 72]  ERROR - plication.impl.ApplicationImpl - Vendor: JetBrains s.r.o 
2017-11-13 15:34:04,799 [ thread 72]  ERROR - plication.impl.ApplicationImpl - OS: Windows 10 
2017-11-13 15:34:04,799 [ thread 72]  ERROR - plication.impl.ApplicationImpl - Last Action:  `

**Comment by ivankolev** [comment]
Ok, so the problem seems to be that we are not implementing an AnkoComponent, as outlined here:
https://github.com/Kotlin/anko/wiki/Anko-Layouts#anko-support-plugin
When I followed the steps there, the preview works properly.

**Comment by yaosongqwe** [comment]
@ivankolev 
Thank you very much.
I have solved that by your way, and then i preview my DSL layout successfully.
