### ISSUE TITLE
Unit test fails using uiThread() inside doAsync()

### ISSUE THREAD

**Issue by FrancoSabadini** [Kotlin/anko#505]
I'm creating some unit tests for my Android app logic and I'm stuck trying to figure out how to make `uiThread()` work in them.

The code I have is very basic:

```kotlin
doAsync {
            // Update the DB

            uiThread {
                // Update LiveData
            }
        }
```

and the error I'm getting is:

```
java.lang.ExceptionInInitializerError
	at org.jetbrains.anko.AsyncKt.uiThread(Async.kt:67)
...
Caused by: java.lang.RuntimeException: Method getMainLooper in android.os.Looper not mocked. See http://g.co/androidstudio/not-mocked for details.
	at android.os.Looper.getMainLooper(Looper.java)
	at org.jetbrains.anko.ContextHelper.<init>(Async.kt:209)
	at org.jetbrains.anko.ContextHelper.<clinit>(Async.kt:208)
	... 12 more
```

Any idea how I can make this work?

**Comment by Ant8** [comment]
just a wild a** guess, but perhaps _InstrumentationRegistry.getInstrumentation().runOnMainSync { }_ would help?

**Comment by FrancoSabadini** [comment]
Thanks for the answer @Ant8. In the end, I ended up moving to coroutines as I thought it was interesting to learn how to use them. I still had this issue in a different way (when using the `UI` constant that is used to run a coroutine on the main thread), so I created some custom code to use my own constant instead of `UI` so that I could override it in tests.

I hope your answer can help other people that are having this issue!
