### ISSUE TITLE
Anko Support: Convert to Anko Layouts DSL (uncaught ExceptionInInitializerError)

### ISSUE THREAD

**Issue by yehorh** [Kotlin/anko#508]
Anko Support
Convert to Anko Layouts DSL (version 0.10.2)

Any xml layout document

Android Studio 3.0
Build #AI-171.4408382, built on October 20, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.12-1-ARCH

Plugin Error: Anko Support threw an uncaught ExceptionInInitializerError.
`null
java.lang.ExceptionInInitializerError
	at org.jetbrains.kotlin.android.xmlconverter.XmlConverter.getWidgetAttributes(XmlConverter.kt:106)
	at org.jetbrains.kotlin.android.xmlconverter.XmlConverter.parseView(XmlConverter.kt:84)
	at org.jetbrains.kotlin.android.xmlconverter.XmlConverter.convert(XmlConverter.kt:51)
	at org.jetbrains.kotlin.android.xmlconverter.XmlConverter.convert$default(XmlConverter.kt:47)
	at org.jetbrains.kotlin.android.xmlconverter.ConvertAction.convert(ConvertAction.kt:147)
	at org.jetbrains.kotlin.android.xmlconverter.ConvertAction.access$convert(ConvertAction.kt:40)
	at org.jetbrains.kotlin.android.xmlconverter.ConvertAction$actionPerformed$1.run(ConvertAction.kt:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1023)
	at org.jetbrains.kotlin.android.xmlconverter.ConvertAction.actionPerformed(ConvertAction.kt:51)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:215)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:232)
	at com.intellij.ide.actions.GotoActionAction.lambda$performAction$4(GotoActionAction.java:334)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionLater$3(TransactionGuardImpl.java:259)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: ../attrs.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at kotlin.io.FilesKt__FileReadWriteKt.readBytes(FileReadWrite.kt:52)
	at kotlin.io.FilesKt.readBytes(Unknown Source)
	at kotlin.io.FilesKt__FileReadWriteKt.readText(FileReadWrite.kt:77)
	at kotlin.io.FilesKt.readText(Unknown Source)
	at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FileReadWrite.kt:77)
	at kotlin.io.FilesKt.readText$default(Unknown Source)
	at org.jetbrains.kotlin.android.attrs.AttrsKt.readResource(Attrs.kt:43)
	at org.jetbrains.kotlin.android.xmlconverter.UtilKt.<clinit>(Util.kt:26)
	... 35 more`

**Comment by 4u7** [comment]
Fixed in 0.10.3, will be released soon
