### ISSUE TITLE
Getting an unknown error on AS 3.2.0-3

### ISSUE THREAD

**Issue by vinukn** [Kotlin/anko#573]
Running sample project,
`02-20 16:55:03.452 4066-4066/org.example.ankodemo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.example.ankodemo, PID: 4066
    java.lang.VerifyError: Verifier rejected class org.jetbrains.anko.internals.AnkoInternals: void org.jetbrains.anko.internals.AnkoInternals.fillIntentArguments(android.content.Intent, kotlin.Pair[]) failed to verify: void org.jetbrains.anko.internals.AnkoInternals.fillIntentArguments(android.content.Intent, kotlin.Pair[]): [0xB] 'this' argument 'Reference: java.lang.Object' not instance of 'Precise Reference: kotlin.Pair' (declaration of 'org.jetbrains.anko.internals.AnkoInternals' appears in /data/app/org.example.ankodemo-9aI-GuXlgtSCxelwwyNkyA==/base.apk)
        at org.example.ankodemo.MainActivityUi.createView(MainActivity.kt:74)
        at org.example.ankodemo.MainActivityUi.createView(MainActivity.kt:37)
        at org.jetbrains.anko.AnkoContextKt.setContentView(AnkoContext.kt:135)
        at org.example.ankodemo.MainActivity.onCreate(MainActivity.kt:16)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by DakotaWhipple** [comment]
Fixed in #571 by updating to 'com.android.tools.build:gradle:3.2.0-alpha04'. Works in Android Studio 3.2-3
