### ISSUE TITLE
Update Anko to use Kotlin 1.3

### ISSUE THREAD

**Issue by paolorotolo** [Kotlin/anko#691]
Anko is preventing me to update to Kotlin 1.3 stable.

Using Anko Courotines with Kotlin 1.3 results in a crash when executing the app:
```
 java.lang.IllegalArgumentException: Must be used with DispatchedContinuation
        at kotlinx.coroutines.experimental.CancellableContinuationImpl.resumeUndispatched(CancellableContinuation.kt:259)
        at kotlinx.coroutines.experimental.android.HandlerContext$scheduleResumeAfterDelay$1.run(HandlerContext.kt:50)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by paolorotolo** [comment]
Probably duplicate of #690, I'm closing this.
