### ISSUE TITLE
Crash using Fragment's ctx after screen rotation

### ISSUE THREAD

**Issue by Ribesg** [Kotlin/anko#71]
````
06-25 14:37:25.830    2059-2059/fr.ribesg.android.encypokedia E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: fr.ribesg.android.encypokedia, PID: 2059
    java.lang.IllegalStateException: getActivity() must not be null
            at org.jetbrains.anko.AnkoPackage$Support$7881aa12.getCtx(Support.kt:80)
            at org.jetbrains.anko.AnkoPackage.getCtx(Unknown Source)
            at fr.ribesg.android.encypokedia.activity.fragment.PkmnFragment.setPkmn(PkmnFragment.kt:64)
            at fr.ribesg.android.encypokedia.activity.MainActivity$Companion.onPkmnSelected(MainActivity.kt:30)
            at fr.ribesg.android.encypokedia.activity.adapter.item.PokemonItem$getView$$inlined$linearLayout$lambda$2.invoke(PokemonItem.kt:38)
            at fr.ribesg.android.encypokedia.activity.adapter.item.PokemonItem$getView$$inlined$linearLayout$lambda$2.invoke(PokemonItem.kt:17)
            at org.jetbrains.anko.AnkoPackage$sam$OnClickListener$9167ff7c.onClick(Listeners.kt)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5257)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
````

Full source of app available on Github, exception thrown [here].

[here]: https://github.com/Ribesg/Encypokedia/blob/fb499fe2519b1e9fc6c22253e8c69c3372ee0db3/PokeApp/src/main/kotlin/fr/ribesg/android/encypokedia/activity/fragment/PkmnFragment.kt#L64

**Comment by yanex** [comment]
I tried to debug your project.
I don't know about the original `getActivity() must not be null` exception cause I couldn't reproduce it, but `PkmnPkmnFragment` does not have an empty constructor (and [it is required](http://stackoverflow.com/questions/10450348/do-fragments-really-need-an-empty-constructor)).

```
java.lang.InstantiationException: can't instantiate class fr.ribesg.android.encypokedia.activity.fragment.PkmnPkmnFragment; no empty constructor
```

is thrown.

**Comment by yanex** [comment]
Also, you save `View` references in `PkmnPkmnFragment` even when an underlying `Activity` is gone. It leads to memory leaks.

You can clean `View` references, for example, in overriden `Fragment.onDetach()` method.

**Comment by Ribesg** [comment]
You're using the latest version, it's a work in progress. Thanks for pointing those errors out.

The version the error occured in is here https://github.com/Ribesg/Encypokedia/tree/fb499fe2519b1e9fc6c22253e8c69c3372ee0db3
