### ISSUE TITLE
Dsl processing error (UNKNOWN): Unable to find message markers.

### ISSUE THREAD

**Issue by pawegio** [Kotlin/anko#72]
When I try to refresh DSL Preview in Activity with layout defined in anko DSL I receive following error:

<img width="547" alt="zrzut ekranu 2015-07-15 o 22 58 24" src="https://cloud.githubusercontent.com/assets/876573/8709855/c65a83a4-2b45-11e5-91f5-44817a3af884.png">

I'm using:
IntelliJ IDEA 14.1.4 Ultimate Edition
kotlin 0.12.613
anko 0.6.3-15

**Comment by yanex** [comment]
Does it happen every time, even in case of very simple layout?

**Comment by pawegio** [comment]
I use simple activity with layout from readme:

```
import android.app.Activity
import android.os.Bundle
import org.jetbrains.anko.*

public class KotlinActivity : Activity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        relativeLayout {
            val name = editText()
            button("Say Hello") {
                onClick { toast("Hello, ${name.text}!") }
            }
        }
    }
}
```
I tried gradle clean & rebuild, removing build dir and invalidating & restarting IntelliJ.

**Comment by pawegio** [comment]
same for Android Studio and clear project

**Comment by snice** [comment]
I am a Chinese developers, also encountered this kind of situation

**Comment by pawegio** [comment]
Occurs also in clear install of Android Studio.

**Comment by wangjiegulu** [comment]
I had same problem.
intellij idea: 14.1.1
kotlin: 0.12.1230
anko: 0.6.3-15
Anko DSL Preview plugin: 0.6.3

**Comment by IceCivet** [comment]
i have also problem, i cannot finish, can help me? thanks

**Comment by sidius** [comment]
kotlin 1.0.0-beta-1038
anko 0.7.2

doesn't work with the simplest layout. gives the exact error as in this issue for a couple of tries and then throws this exception:

java.lang.NoSuchMethodError: org.jetbrains.android.facet.AndroidFacet.isGradleProject()Z
        at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager.render(DslPreviewToolWindowManager.kt:265)
        at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager$RefreshDslAction.actionPerformed(DslPreviewToolWindowManager.kt:365)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
        at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:163)
        at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:127)
        at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:304)
        at java.awt.Component.processEvent(Component.java:6290)
        at java.awt.Container.processEvent(Container.java:2234)
        at java.awt.Component.dispatchEventImpl(Component.java:4881)
        at java.awt.Container.dispatchEventImpl(Container.java:2292)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
        at java.awt.Container.dispatchEventImpl(Container.java:2278)
        at java.awt.Window.dispatchEventImpl(Window.java:2739)
        at java.awt.Component.dispatchEvent(Component.java:4703)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
        at java.awt.EventQueue.access$400(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:697)
        at java.awt.EventQueue$3.run(EventQueue.java:691)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:719)
        at java.awt.EventQueue$4.run(EventQueue.java:717)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.jav

**Comment by liaction** [comment]
open the DSL Preview  and press Refresh 



	class Test : Activity() {
	    override fun onCreate(savedInstanceState: Bundle?) {
	        super.onCreate(savedInstanceState)
	        verticalLayout {
	            textView {
	                text = "Hello Kotlin !"
	            }
	        }
	    }
	}

kotlin 1.0.0-beta-1103
anko 0.7.2

org.jetbrains.android.facet.AndroidFacet.isGradleProject()Z
java.lang.NoSuchMethodError: org.jetbrains.android.facet.AndroidFacet.isGradleProject()Z
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager.render(DslPreviewToolWindowManager.kt:265)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewToolWindowManager$RefreshDslAction.actionPerformed(DslPreviewToolWindowManager.kt:365)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:163)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:127)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:304)
	at java.awt.Component.processEvent(Component.java:6270)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4861)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4687)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:723)
	at java.awt.EventQueue.access$200(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:682)
	at java.awt.EventQueue$3.run(EventQueue.java:680)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:696)
	at java.awt.EventQueue$4.run(EventQueue.java:694)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:693)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:244)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:163)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:151)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:147)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:139)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:97)

**Comment by yanex** [comment]
New DSL preview is coming soon, so this bug will eventually become obsolete.
