### ISSUE TITLE
Android Studio 3.3.1 , Anko support 0.10.7 grey screeen no preview 

### ISSUE THREAD

**Issue by louaydhyeb** [Kotlin/anko#732]
Using this configuration i can't see any preview of Anko Preview, only a grey screen help i'm Blocked

**Comment by sopracreau** [comment]
I have the same problem  : 

My version 
    ext.kotlin_version = '1.3.20'
    ext.anko_version = '0.10.8'

My stacktrace
2019-04-29 15:19:25,562 [ thread 24]  ERROR - plication.impl.ApplicationImpl - java.lang.ClassCastException@5b31c043 
java.lang.IllegalArgumentException: java.lang.ClassCastException@5b31c043
	at sun.reflect.GeneratedConstructorAccessor367.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewClassResolver$Companion.createTypeMapper(DslPreviewClassResolver.kt:131)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewClassResolver$Companion.access$createTypeMapper(DslPreviewClassResolver.kt:122)
	at org.jetbrains.kotlin.android.dslpreview.DslPreviewClassResolver.resolveClassDescription(DslPreviewClassResolver.kt:116)
	at org.jetbrains.kotlin.android.dslpreview.UpdateActivityNameTask.processRequest(UpdateActivityNameTask.kt:44)
	at org.jetbrains.kotlin.android.dslpreview.UpdateActivityNameTask.processRequest(UpdateActivityNameTask.kt:12)
	at org.jetbrains.kotlin.idea.util.LongRunningReadTask$1$1.run(LongRunningReadTask.java:110)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:930)
	at org.jetbrains.kotlin.idea.util.LongRunningReadTask$3.run(LongRunningReadTask.java:226)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at org.jetbrains.kotlin.idea.util.LongRunningReadTask.runWithWriteActionPriority(LongRunningReadTask.java:223)
	at org.jetbrains.kotlin.idea.util.LongRunningReadTask$1.run(LongRunningReadTask.java:105)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2019-04-29 15:19:25,563 [ thread 24]  ERROR - plication.impl.ApplicationImpl - Android Studio 3.3.1  Build #AI-182.5107.16.33.5264788 
2019-04-29 15:19:25,563 [ thread 24]  ERROR - plication.impl.ApplicationImpl - JDK: 1.8.0_152-release 
2019-04-29 15:19:25,563 [ thread 24]  ERROR - plication.impl.ApplicationImpl - VM: OpenJDK 64-Bit Server VM 
2019-04-29 15:19:25,563 [ thread 24]  ERROR - plication.impl.ApplicationImpl - Vendor: JetBrains s.r.o 
2019-04-29 15:19:25,563 [ thread 24]  ERROR - plication.impl.ApplicationImpl - OS: Mac OS X 
2019-04-29 15:19:25,563 [ thread 24]  ERROR - plication.impl.ApplicationImpl - Last Action: ShowLog 
2019-04-29 15:19:26,293 [der Thread]   WARN - ls.idea.rendering.RenderLogger - Class not found __anko.preview.View 
2019-04-29 15:19:26,326 [der Thread]   WARN - ls.idea.rendering.RenderLogger - Class not found __anko.preview.View

**Comment by iskmz** [comment]
not fixed on android studio 3.4.0 either 
same grey screen in the preview, no matter if project built or not 
anko support version:  latest ...Oct 12, 2018 ... Version 0.10.7-2
ext.kotlin_version = '1.3.21'
ext.anko_version='0.10.8'

**Comment by MayurPrajapati** [comment]
Any update on this?

**Comment by tanks007** [comment]
Getting IDE fatal error, exception in anko support plugin, Waiting for update

**Comment by tanks007** [comment]
93 exceptions saying : argument type mismatch
java.lang.IllegalArgumentException: argument type mismatch

**Comment by tanks007** [comment]
As per the responses and updates, the project seems to be discontinued.
It would have been great if they announced it officially and/or mark the repository as deprecated, this would make us clear to architect/migrate our project on other UI platforms.

**Comment by AnhDTN** [comment]
i have a question for AnKo layout, i don't know Anko still being deleloped and using in android ?? because i verry love it when read and start with it. but i don't know if it has a future?
